GluuFederation/inbound-saml

- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- SECURITY.md
> chore: repository setup

- README.md
- package-lock.json
- package.json
- src/get-saml-metadata/src/entities/types/ValueObject.spec.ts
- src/get-saml-metadata/src/entities/types/ValueObject.test.ts
> test: add missing tests to `ValueObject`

- README.md
Mark delivered features as done
> docs(readme): mark as done

- openapi.json
> feat: add OpenApi json file

- .github/workflows/bdd.yml
- .github/workflows/test.yml
- README.md
- src/sp-proxy/src/use-cases/GetTrByHostInteractor.spec.ts
- src/sp-proxy/src/use-cases/GetTrByHostInteractor.ts
- src/sp-proxy/src/use-cases/io-models/GetTrByHostRequestUseCaseParams.ts
- src/sp-proxy/src/use-cases/io-models/GetTrByHostResponseUseCaseParams.ts
- src/sp-proxy/src/use-cases/ports/IGetTrByHostGateway.ts
> feat(GetTrByHost): add interactor to execute request

- .vscode/launch.json
- docker-compose-test.yml
- src/sp-proxy/src/interface-adapters/README.md
- `.vscode/launch.json` for debug
- folders `README`
- docker compose for tests integration
> chore: aditional misc chores

- packages/sp-proxy/src/interface-adapters/utils/formatters/BaseKeyCertFormatter.spec.ts
- packages/sp-proxy/src/interface-adapters/utils/formatters/BaseKeyCertFormatter.test.ts
- packages/sp-proxy/src/interface-adapters/utils/formatters/BaseKeyCertFormatter.ts
- packages/sp-proxy/src/interface-adapters/utils/formatters/GenerateMetadataFormatter.ts
- packages/sp-proxy/src/use-cases/ReadSpProxyConfigInteractor.spec.ts
- packages/sp-proxy/src/use-cases/ReadSpProxyConfigInteractor.ts
- packages/sp-proxy/src/use-cases/io-models/ReadSpProxyConfigRequestUseCaseParams.ts
- packages/sp-proxy/src/use-cases/io-models/ReadSpProxyConfigResponseUseCaseParams.ts
> feat(readSpProxyConfig): add use case interactor

- packages/sp-proxy/src/interface-adapters/delivery/ReadSpProxyConfigController.spec.ts
- packages/sp-proxy/src/interface-adapters/delivery/ReadSpProxyConfigController.ts
- packages/sp-proxy/src/interface-adapters/delivery/dtos/IReadSpProxyConfigRequest.ts
> feat(readProxyCfg): add controller to dispatch request

- packages/sp-proxy/src/interface-adapters/delivery/ReadSpProxyConfigPresenter.spec.ts
- packages/sp-proxy/src/interface-adapters/delivery/ReadSpProxyConfigPresenter.ts
- packages/sp-proxy/src/interface-adapters/delivery/dtos/IReadSpProxyConfigResponse.ts
- packages/sp-proxy/src/interface-adapters/delivery/mappers/ReadSpProxyConfigPresenterMapper.spec.ts
- packages/sp-proxy/src/interface-adapters/delivery/mappers/ReadSpProxyConfigPresenterMapper.ts
> feat(readSpProxyConfig): add result dispatcher

- packages/sp-proxy/src/interface-adapters/delivery/mappers/ReadSpConfigControllerMapper.spec.ts
- packages/sp-proxy/src/interface-adapters/delivery/mappers/ReadSpProxyConfigControllerMapper.ts
> feat(readSpProxyConfig): add controller mapper

- packages/sp-proxy/src/use-cases/helpers/pickDefaultSso.spec.ts
- packages/sp-proxy/src/use-cases/helpers/pickDefaultSso.ts
> feat(trustRelation): change default sso binding to HTTP-Redirect

- packages/sp-proxy/src/frameworks-drivers/main/routes/addTrFromMetadataRouter.test.ts
- packages/sp-proxy/src/frameworks-drivers/main/routes/authenticateCallbackRouter.test.ts
- packages/sp-proxy/src/frameworks-drivers/main/routes/authenticateRouter.test.ts
- packages/sp-proxy/src/interface-adapters/api/AddTrFromMetadataFacade.test.ts
- packages/sp-proxy/src/interface-adapters/api/GetTrByHostFacade.test.ts
- packages/sp-proxy/src/interface-adapters/data/OxTrustAddTrustRelation.spec.ts
- packages/sp-proxy/src/interface-adapters/data/OxTrustAddTrustRelation.ts
> fix: UMA token handling in `AddTrustRelation`

- packages/sp-proxy/src/interface-adapters/data/helpers/UmaAuthenticator.spec.ts
- packages/sp-proxy/src/interface-adapters/data/helpers/UmaAuthenticator.ts
> fix(UmaAuthenticator): add needed content-type headers

- packages/sp-proxy/src/interface-adapters/config/env.ts
All variables should have `INBOUND_SAML` as prefix.
> fix(config): update configuration env variables names 

- .gitignore
- package.json
Start script needed for `NODE_ENV=prod`
> feat: add start script to production env

- docs/getting_started.md
- packages/sp-proxy/package.json
- setup/README.md
- setup/inboundsaml.service
System unit file to run services.
> feat: add system unit

- docs/getting_started.md
> docs: add note about `https` being required OAuth2

- .github/workflows/bdd.yml
- .github/workflows/test.yml
- lerna.json
> feat: update node version

- packages/sp-proxy/src/interface-adapters/config/PersistenceConfig.spec.ts
- packages/sp-proxy/src/interface-adapters/config/env.ts
> fix(config): return default completePath

- package.json
- packages/sp-proxy/src/interface-adapters/data/OxTrustAddTrustRelation.spec.ts
- packages/sp-proxy/src/interface-adapters/data/OxTrustGetTrByHost.spec.ts
- yarn.lock
Fix [CVE-2022-24772](https://github.com/advisories/GHSA-x4jg-mjrx-434g)
Superseeds #126
> fix(security): update axios

- package.json
- packages/sp-proxy/src/interface-adapters/data/helpers/UmaAuthenticator.ts
- yarn.lock
> fix: update Winston
